import type { LifeFlowCategory } from "@/features/ledger/model"

/** 系统默认的 14 个生命流向分类，对齐 domain-model.md */
export const DEFAULT_LIFE_FLOW_CATEGORIES: LifeFlowCategory[] = [
  {
    id: "survival",
    name: "生存维持",
    description: "维持基本生活",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 1,
    isDefault: true,
  },
  {
    id: "work_cost",
    name: "工作代价",
    description: "为了工作产生的成本",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 2,
    isDefault: true,
  },
  {
    id: "health",
    name: "身体维护",
    description: "让身体保持可持续",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 3,
    isDefault: true,
  },
  {
    id: "joy",
    name: "精神回血",
    description: "恢复情绪和能量",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 4,
    isDefault: true,
  },
  {
    id: "relationship",
    name: "关系连接",
    description: "与重要的人建立连接",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 5,
    isDefault: true,
  },
  {
    id: "growth",
    name: "成长复利",
    description: "让未来更好的投入",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 6,
    isDefault: true,
  },
  {
    id: "freedom",
    name: "自由积累",
    description: "把当下资源投入未来自由",
    direction: "expense",
    statEffect: "freedom_increase",
    sortOrder: 7,
    isDefault: true,
  },
  {
    id: "numbness",
    name: "逃避麻木",
    description: "情绪性、冲动性、无意识消费",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 8,
    isDefault: true,
  },
  {
    id: "accident",
    name: "意外事件",
    description: "非计划突发支出",
    direction: "expense",
    statEffect: "consume",
    sortOrder: 9,
    isDefault: true,
  },
  {
    id: "salary",
    name: "工资收入",
    description: "主业收入",
    direction: "income",
    statEffect: "energy_gain",
    sortOrder: 10,
    isDefault: true,
  },
  {
    id: "side_income",
    name: "副业收入",
    description: "主业外收入",
    direction: "income",
    statEffect: "energy_gain",
    sortOrder: 11,
    isDefault: true,
  },
  {
    id: "refund",
    name: "退款返还",
    description: "购物退款、订单取消退款、报销返还",
    direction: "income",
    statEffect: "expense_reversal",
    sortOrder: 12,
    isDefault: true,
  },
  {
    id: "freedom_withdraw",
    name: "储能解冻",
    description: "从储蓄或投资中取出",
    direction: "income",
    statEffect: "freedom_decrease",
    sortOrder: 13,
    isDefault: true,
  },
  {
    id: "unknown",
    name: "未判断",
    description: "新场景、新现金流",
    direction: "neutral",
    statEffect: "ignore",
    sortOrder: 14,
    isDefault: true,
  },
]

export function getDefaultLifeFlowCategories(): LifeFlowCategory[] {
  return DEFAULT_LIFE_FLOW_CATEGORIES.map((lifeFlowCategory) => ({
    ...lifeFlowCategory,
  }))
}
